#!/bin/bash

# necessary programs
sudo apt install build-essentials python3-pip gfortran gnuplot

# better stuff
sudo apt install bat zsh zplug

# lsd as a replacement to ls
wget https://github.com/lsd-rs/lsd/releases/download/v1.0.0/lsd-musl_1.0.0_amd64.deb && sudo dpkg -i lsd-musl_1.0.0_amd64.deb

# terminal and shell
sudo apt install kitty
cp -r .config/kitty ~/.config/
cp -r .config/zshrc ~/.zshrc

# WINE for running Windows Programs
printf "\e[1;32mInstall Wine for running Windows programs inside Linux? [yes/no]\e[0m\n"
read winepr
if [[ $winepr = yes ]]; then
	sudo dpkg --add-architecture i386
	sudo apt update
	sudo apt install wine wine64 wine32

	printf "\e[1;32mInstall LTSpice? [yes/no]\e[0m\n"
	read ltspr
	if [[ $ltspr = yes]]; then
		# Setup LTSpice
		wget https://ltspice.analog.com/software/LTspice64.exe
		wine LTspice64.exe
	fi
fi
