#!/bin/bash

# necessary programs
sudo apt install build-essentials python3 python3-pip gfortran gnuplot

# better stuff
sudo apt install bat zsh zplug

# lsd as a replacement to ls
wget https://github.com/lsd-rs/lsd/releases/download/v1.0.0/lsd-musl_1.0.0_amd64.deb && sudo dpkg -i lsd-musl_1.0.0_amd64.deb

# terminal and shell
sudo apt install kitty
cp -r .config/kitty ~/.config/
cp -r .config/zshrc ~/.zshrc
