add_newline = false

[line_break]
disabled = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[package]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[conda]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

